INSERT INTO mudurluk (ad, sorumluluk_alani, aktif) VALUES
('Fen İşleri Müdürlüğü',
 'Asfalt yama ve yol bakımı, kaldırım yapımı ve onarımı, yağmur suyu ızgaraları, sokak aydınlatma direkleri, üstyapı çalışmaları, bordür taşı, menfez ve köprü bakımı.',
 true),
('Park ve Bahçeler Müdürlüğü',
 'Park, yeşil alan ve refüjlerin bakımı; ağaç dikimi, budama ve kesimi; çocuk oyun grupları ve spor aletlerinin bakım/onarımı; süs havuzları ve peyzaj çalışmaları.',
 true),
('Temizlik İşleri Müdürlüğü',
 'Evsel katı atık toplama ve nakliyesi, cadde/sokak süpürme, çöp konteyneri temini ve bakımı, pazar yeri temizliği, konteyner alanlarının hijyeni.',
 true),
('Zabıta Müdürlüğü',
 'Kaldırım ve yol işgali denetimi, seyyar satıcı ve işyeri ruhsat denetimi, gürültü ve çevre kirliliği şikayetleri, pazar yeri düzeni, kaçak yapı/işgal tespiti.',
 true),
('İmar ve Şehircilik Müdürlüğü',
 'İmar durumu sorgulama ve belgesi, imar planı değişiklik talepleri, yapı ruhsatı ve yapı kullanma izni öncesi imar uygunluk incelemesi, parselasyon işlemleri.',
 true),
('Ruhsat ve Denetim Müdürlüğü',
 'İşyeri açma ve çalışma ruhsatları, yapı ruhsatı başvuruları, sıhhi ve gayrisıhhi müessese denetimleri, ruhsatsız faaliyet şikayetleri.',
 true),
('Veteriner İşleri Müdürlüğü',
 'Başıboş sokak hayvanları (köpek, kedi) ile ilgili şikayetler, hayvan barınağı işlemleri, kısırlaştırma/aşılama, hayvan ısırma vakaları, kuduz şüphesi ihbarları.',
 true),
('Su ve Kanalizasyon Müdürlüğü',
 'İçme suyu şebekesi arızaları, su birikintisi ve su baskını şikayetleri, kanal/rögar tıkanıklığı, yağmur suyu drenaj sorunları, atık su kokusu şikayetleri.',
 true),
('Sosyal Yardım İşleri Müdürlüğü',
 'Nakdi ve ayni yardım başvuruları (gıda, kömür, kira desteği), muhtaç aile tespiti, engelli ve yaşlı desteği başvuruları, öğrenci burs başvuruları.',
 true),
('Kültür ve Sosyal İşler Müdürlüğü',
 'Kültürel etkinlik ve kurs başvuruları, halk eğitim faaliyetleri, kütüphane hizmetleri, sosyal tesis kullanım talepleri, düğün salonu rezervasyonu.',
 true);
